FROM openjdk:11
COPY Central/target/*-jar-with-dependencies.jar /usr/app/app.jar

ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.7.3/wait /wait
RUN chmod +x /wait

COPY Central/central.sh /run.sh
ENTRYPOINT ["sh","/run.sh"]
